spring:
  application:
    name: ToDoList
  datasource:
    url: jdbc:mysql://localhost:3306/springbootlearning
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      jdbc:
        time_zone: UTC
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8088